# Generated by Django 3.2.4 on 2021-06-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('src', models.ImageField(blank=True, null=True, upload_to='upload/categorys', verbose_name='分类图片')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='是否删除')),
                ('descript', models.CharField(blank=True, max_length=255, verbose_name='商品描述')),
                ('detail', models.TextField(blank=True, verbose_name='商品详情模板')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='是否上架')),
                ('like_num', models.IntegerField(blank=True, null=True, verbose_name='商品收藏量')),
            ],
            options={
                'verbose_name': '商品(Spu)',
                'verbose_name_plural': '商品(Spu)',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '商品相册', 'verbose_name_plural': '商品相册'},
        ),
        migrations.AddField(
            model_name='image',
            name='is_delete',
            field=models.BooleanField(default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='image',
            name='src',
            field=models.ImageField(default='', upload_to='upload', verbose_name='商品图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='是否删除')),
                ('attribute', models.TextField(null=True, verbose_name='属性名:属性值，多个属性使用"逗号"隔开')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='真实价格')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('id_goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='商品(Spu)')),
            ],
            options={
                'verbose_name': '商品(Sku)',
                'verbose_name_plural': '商品(Sku)',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='gallery',
            field=models.ManyToManyField(related_name='goods_gallery', to='goods.Image', verbose_name='商品图片集合'),
        ),
        migrations.AddField(
            model_name='goods',
            name='id_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.categorys', verbose_name='商品分类ID'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.image', verbose_name='商品图片'),
        ),
    ]
